In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import csv
import time
import chardet

import os

import PublicDataReader as pdr

D:\seoulmate\.venv\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.7) doesn't match a supported version!
  warnings.warn(

In [97]:
# 공간 데이터
space_file = "서울시_행정동_영역.csv"

# 이동 데이터
base_dir = r"D:\seoulmate\서울시_행정동_이동"
month_dirs = {
    "tpss_emd_odps_202408",
    "tpss_emd_odps_202409",
    "tpss_emd_odps_202410",
    "tpss_emd_odps_202411",
    "tpss_emd_odps_202412",
    "tpss_emd_odps_202501",
    "tpss_emd_odps_202502",
    "tpss_emd_odps_202503",
    "tpss_emd_odps_202504",
    "tpss_emd_odps_202505",
    "tpss_emd_odps_202506",
    "tpss_emd_odps_202507",
    "tpss_emd_odps_202508",
    "tpss_emd_odps_202509",
    "tpss_emd_odps_202510",
    "tpss_emd_odps_202511",
    "tpss_emd_odps_202512",
    "tpss_emd_odps_202601",
    "tpss_emd_odps_202602",
    "tpss_emd_odps_202603",
}


# 행정동ID-행정동코드-법정동코드 매핑

edm_mapping_name = "서울시_행정동ID_행정동코드_맵핑.csv"


#
# 법정동 위치크기 + 일단위 행정동 대중교통/버스/지하철 승차수
#
# 법정동코드|법정동이름|행정동ID|행정동이름|AREA_M2|LAT|LON|전체승객수|지하철승객수|버스승객수
spatiotemporal_name = "서울시_행정동_시공간_202401_202603.csv"

In [98]:
space_df = pd.read_csv(space_file, encoding="utf-8-sig")

print(f"행정동코드 갯수:{len(space_df['adm_cd2'].unique())}")
space_df.head(10)

행정동코드 갯수:426

      adm_cd2                 adm_nm  AREA_M2        LAT       LON
0  1111053000          서울특별시 종로구 사직동  1165780  126.97014  37.57411
1  1111054000          서울특별시 종로구 삼청동  1361445  126.98111  37.58801
2  1111055000          서울특별시 종로구 부암동  2202073  126.96256  37.59670
3  1111056000          서울특별시 종로구 평창동  9017316  126.96927  37.61396
4  1111057000          서울특별시 종로구 무악동   467575  126.95899  37.57774
5  1111058000          서울특별시 종로구 교남동   345990  126.96416  37.57105
6  1111060000          서울특별시 종로구 가회동   605383  126.98662  37.58268
7  1111061500  서울특별시 종로구 종로1·2·3·4가동  2394166  126.98973  37.57508
8  1111063000      서울특별시 종로구 종로5·6가동   633463  127.00424  37.57302
9  1111064000          서울특별시 종로구 이화동   755902  127.00307  37.57969

In [99]:

# 법정동 갯수는 467개
# 행정동 갯수는 426개

edm_mapping_df = pd.read_csv(edm_mapping_name, encoding="utf-8-sig")


print(f"맵핑 갯수:{len(edm_mapping_df)}, 행정동ID 갯수:{len(edm_mapping_df['행정동_ID'].unique())}, 행정동코드 갯수:{len(edm_mapping_df['행정동코드'].unique())}")

edm_mapping_df.head(2)

맵핑 갯수:426, 행정동ID 갯수:426, 행정동코드 갯수:426

     행정동_ID       행정동코드  행정동이름
0  11010720  1111051500  청운효자동
1  11010530  1111053000    사직동

In [100]:
# 1:1 인지 확인

#
# edm_mapping_df["cnt"] = edm_mapping_df.groupby("행정동_ID")["행정동코드"].transform("count")
#
# print(len(edm_mapping_df))
#
# dup_df = edm_mapping_df[edm_mapping_df["cnt"]!=1]
#
# print(len(dup_df))
#
# dup_df

In [101]:


# 기존 spatiotemporal_name 삭제
if os.path.exists(spatiotemporal_name):
    os.remove(spatiotemporal_name)


# spatiotemporal_name 생성
for month_dir in sorted(month_dirs):

    passenger_dir = os.path.join(base_dir, month_dir)

    files = os.listdir(passenger_dir)

    for file in files:

        passenger_file = os.path.join(passenger_dir, file)

        print(f"{passenger_file} 처리")

        try:
            passenger_df = pd.read_csv(passenger_file,encoding="cp949")
        except:
            passenger_df = pd.read_csv(passenger_file,encoding="utf-8-sig")

        #print(passenger_df.head(10))

        # 시작을 모르면 제외
        passenger_df = passenger_df[passenger_df["시작_행정동_ID"]!=-1]

        #
        # 시작 행정동기준으로 합친다
        #
        passenger_sum_df = passenger_df.groupby(["기준_날짜","시작_행정동_ID"],as_index=False)[
            ["전체_승객_수 (명)","지하철_승객_수 (명)","버스_승객_수 (명)"]
        ].sum()

        #
        # print(f"갯수:{len(passenger_sum_df)}")
        # print(passenger_sum_df.head(2))


        # 행정동코드와 합치기
        spatiotemporal_df = pd.merge(
            edm_mapping_df,
            passenger_sum_df,
            left_on="행정동_ID",
            right_on="시작_행정동_ID",
            how="right"
        )

        # # 컬럼 이름 변경
        # print(f"갯수:{len(spatiotemporal_df)}")
        # print(spatiotemporal_df.head(2))


        # 영역과 합치기
        spatiotemporal_df = pd.merge(
            space_df,
            spatiotemporal_df,
            left_on="adm_cd2",
            right_on="행정동코드",
            how="right"
        )


        # int64
        cols = ["행정동코드","행정동_ID","AREA_M2"]
        spatiotemporal_df[cols] = spatiotemporal_df[cols].astype("Int64")



        # # 컬럼 이름 변경
        # print(f"갯수:{len(spatiotemporal_df)}")
        # print(spatiotemporal_df.head(2))

        spatiotemporal_df.rename(columns={
            "전체_승객_수 (명)":"전체승객수",
            "지하철_승객_수 (명)":"지하철승객수",
            "버스_승객_수 (명)":"버스승객수"
                        })[["기준_날짜",
                           "행정동코드",
                           "행정동이름",
                           "행정동_ID",
                           "AREA_M2",
                           "LAT",
                           "LON",
                           "전체승객수",
                           "지하철승객수",
                           "버스승객수"]].to_csv(
            spatiotemporal_name,
            index=False,
            header=not os.path.exists(spatiotemporal_name),
            mode="a",
            encoding="utf-8-sig")

D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240801.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240802.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240803.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240804.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240805.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240806.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240807.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240808.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240809.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240810.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240811.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240812.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240813.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240814.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240815.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240816.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240817.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240818.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240819.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240820.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240821.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240822.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240823.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240824.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240825.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240826.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240827.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240828.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240829.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240830.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202408\tpss_emd_odps_20240831.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240901.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240902.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240903.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240904.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240905.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240906.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240907.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240908.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240909.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240910.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240911.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240912.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240913.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240914.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240915.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240916.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240917.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240918.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240919.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240920.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240921.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240922.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240923.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240924.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240925.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240926.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240927.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240928.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240929.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202409\tpss_emd_odps_20240930.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241001.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241002.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241003.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241004.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241005.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241006.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241007.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241008.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241009.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241010.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241011.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241012.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241013.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241014.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241015.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241016.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241017.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241018.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241019.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241020.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241021.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241022.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241023.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241024.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241025.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241026.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241027.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241028.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241029.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241030.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202410\tpss_emd_odps_20241031.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241101.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241102.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241103.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241104.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241105.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241106.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241107.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241108.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241109.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241110.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241111.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241112.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241113.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241114.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241115.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241116.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241117.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241118.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241119.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241120.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241121.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241122.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241123.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241124.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241125.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241126.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241127.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241128.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241129.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202411\tpss_emd_odps_20241130.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241201.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241202.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241203.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241204.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241205.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241206.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241207.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241208.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241209.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241210.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241211.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241212.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241213.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241214.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241215.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241216.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241217.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241218.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241219.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241220.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241221.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241222.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241223.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241224.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241225.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241226.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241227.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241228.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241229.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241230.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202412\tpss_emd_odps_20241231.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250101.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250102.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250103.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250104.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250105.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250106.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250107.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250108.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250109.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250110.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250111.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250112.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250113.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250114.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250115.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250116.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250117.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250118.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250119.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250120.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250121.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250122.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250123.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250124.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250125.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250126.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250127.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250128.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250129.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250130.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202501\tpss_emd_odps_20250131.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250201.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250202.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250203.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250204.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250205.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250206.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250207.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250208.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250209.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250210.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250211.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250212.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250213.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250214.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250215.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250216.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250217.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250218.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250219.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250220.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250221.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250222.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250223.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250224.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250225.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250226.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250227.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202502\tpss_emd_odps_20250228.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250301.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250302.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250303.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250304.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250305.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250306.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250307.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250308.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250309.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250310.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250311.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250312.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250313.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250314.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250315.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250316.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250317.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250318.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250319.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250320.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250321.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250322.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250323.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250324.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250325.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250326.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250327.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250328.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250329.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250330.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202503\tpss_emd_odps_20250331.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250401.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250402.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250403.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250404.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250405.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250406.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250407.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250408.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250409.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250410.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250411.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250412.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250413.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250414.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250415.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250416.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250417.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250418.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250419.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250420.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250421.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250422.csv 처리
D:\seoulmate\서울시_행정동_이동\tpss_emd_odps_202504\tpss_emd_odps_20250423.csv 처리

In [7]:
# 월단위를 생성

monthly_spatiotemporal_df = pd.read_csv("서울시_행정동_시공간_일단위_202408_202603.csv", encoding="utf-8-sig")


monthly_spatiotemporal_df["YYYYMM"] = pd.to_datetime(
    monthly_spatiotemporal_df["기준_날짜"], format="%Y%m%d").dt.strftime("%Y%m")

index_cols = [
    "YYYYMM",
    "행정동코드"
]

sum_cols = [
    "전체승객수",
    "지하철승객수",
    "버스승객수"
]


monthly_spatiotemporal_df = monthly_spatiotemporal_df.groupby(index_cols,as_index=False).agg({
        "행정동이름": "first",
        "AREA_M2": "first",
        "LAT": "first",
        "LON": "first",
        "전체승객수": "sum",
        "지하철승객수": "sum",
        "버스승객수": "sum",
    })


monthly_spatiotemporal_df.to_csv("서울시_행정동_시공간_월단위_202408_202603.csv", index=False, encoding="utf-8-sig")


print(f"갯수: {len(monthly_spatiotemporal_df)}")
monthly_spatiotemporal_df.head(2)

갯수: 8513

,YYYYMM,행정동코드,행정동이름,AREA_M2,LAT,LON,전체승객수,지하철승객수,버스승객수
0,202408,1.111052e+09,청운효자동,2438307.0,126.97042,37.58466,252717,0,252717
1,202408,1.111053e+09,사직동,1165780.0,126.97014,37.57411,2375818,1557165,818653

In [4]:
#

s_df = pd.read_csv("../data/서울시_행정동_시공간_월단위_202408_202603.csv", encoding="utf-8-sig")


s_df[["YYYYMM","행정동코드","행정동이름","AREA_M2","LAT","LON","전체승객수"]].to_csv(
    "../data/서울시_행정동_시공간_월단위_202408_202603_base.csv", index=False, encoding="utf-8-sig")