In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import csv
import time
import chardet

import os

import PublicDataReader as pdr

D:\seoulmate\.venv\lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.4.3)/charset_normalizer (3.4.7) doesn't match a supported version!
  warnings.warn(

In [2]:
# 공간 데이터
space_file = r"../data/서울시_행정동_공간_base.csv"

# 이동 데이터
base_dir = r"D:\seoulmate\서울시_행정동_인구"
month_dirs = {
    "250_ORGN_CT_202408",
    "250_ORGN_CT_202409",
    "250_ORGN_CT_202410",
    "250_ORGN_CT_202411",
    "250_ORGN_CT_202412",
    "250_ORGN_CT_202501",
    "250_ORGN_CT_202502",
    "250_ORGN_CT_202503",
    "250_ORGN_CT_202504",
    "250_ORGN_CT_202505",
    "250_ORGN_CT_202506",
    "250_ORGN_CT_202507",
    "250_ORGN_CT_202508",
    "250_ORGN_CT_202509",
    "250_ORGN_CT_202510",
    "250_ORGN_CT_202511",
    "250_ORGN_CT_202512",
    "250_ORGN_CT_202601",
    "250_ORGN_CT_202602",
    "250_ORGN_CT_202603",
    "250_ORGN_CT_202604",
}


# 행정동ID-행정동코드-법정동코드 매핑

edm_mapping_name = r"../data/서울시_행정동ID_행정동코드_맵핑_base.csv"


monthly_population_name = r"../data/서울시_행정동_인구_월단위_202406_202604.csv"

daily_population_name = r"../data/서울시_행정동_인구_일단위_202406_202604.csv"

In [3]:

# 법정동 갯수는 467개
# 행정동 갯수는 426개

edm_mapping_df = pd.read_csv(edm_mapping_name, encoding="utf-8-sig")


print(f"맵핑 갯수:{len(edm_mapping_df)}, 행정동ID 갯수:{len(edm_mapping_df['행정동_ID'].unique())}, 행정동코드 갯수:{len(edm_mapping_df['행정동코드'].unique())}")

edm_mapping_df.head(2)

맵핑 갯수:426, 행정동ID 갯수:426, 행정동코드 갯수:426

     행정동_ID       행정동코드 행정동_명칭 자치구_명칭
0  11010720  1111051500  청운효자동    종로구
1  11010530  1111053000    사직동    종로구

In [15]:
# 1:1 인지 확인

#
# edm_mapping_df["cnt"] = edm_mapping_df.groupby("행정동_ID")["행정동코드"].transform("count")
#
# print(len(edm_mapping_df))
#
# dup_df = edm_mapping_df[edm_mapping_df["cnt"]!=1]
#
# print(len(dup_df))
#
# dup_df

In [5]:



columns = [
    "일자","시각","행정동코드","순위","대도시권거주지코드",
    "생활인구합계"
]


# 기존 spatiotemporal_name 삭제
if os.path.exists(daily_population_name):
    os.remove(daily_population_name)


# spatiotemporal_name 생성
for month_dir in sorted(month_dirs):

    people_dir = os.path.join(base_dir, month_dir)

    files = os.listdir(people_dir)

    for file in files:

        people_file = os.path.join(people_dir, file)

        print(f"{people_file} 처리")

        try:
            people_df = pd.read_csv(people_file,
                                    encoding="cp949",
                                    header=None,
                                    names=columns,
                                    usecols=range(len(columns)),
                                    dtype=str)
        except:
            people_df = pd.read_csv(people_file,
                                    encoding="utf-8-sig",
                                    header=None,
                                    names=columns,
                                    usecols=range(len(columns)),
                                    dtype=str)



        # 시작을 모르면 제외
        people_df = people_df[
            people_df["행정동코드"].notna() &
            (people_df["행정동코드"] != "-1")
        ]


        people_df = people_df[["일자","행정동코드","생활인구합계"]].copy()


        people_df["생활인구합계"] = pd.to_numeric(
           people_df["생활인구합계"],
            errors="coerce"
        )

        people_df["생활인구합계"] = (
            people_df["생활인구합계"]
            .fillna(0)
            .astype(int)
        )


        people_sum_df = people_df.groupby(["일자","행정동코드"],as_index=False).agg({
        "생활인구합계": "sum",
        })


        print(f"갯수:{len(people_sum_df)}")
        print(people_sum_df.head(2))

        people_sum_df.to_csv(
            daily_population_name,
            index=False,
            header=not os.path.exists(daily_population_name),
            mode="a",
            encoding="utf-8-sig")

#        break
#    break

D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240801.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240801  11110515  345452
1  20240801  11110530  818959
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240802.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240802  11110515  350072
1  20240802  11110530  789719
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240803.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240803  11110515  352967
1  20240803  11110530  509701
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240804.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240804  11110515  322000
1  20240804  11110530  459308
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240805.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240805  11110515  327009
1  20240805  11110530  731552
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240806.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240806  11110515  316420
1  20240806  11110530  778483
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240807.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240807  11110515  326103
1  20240807  11110530  807259
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240808.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240808  11110515  325421
1  20240808  11110530  805853
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240809.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240809  11110515  335501
1  20240809  11110530  794494
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240810.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240810  11110515  339256
1  20240810  11110530  530183
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240811.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240811  11110515  323931
1  20240811  11110530  478401
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240812.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240812  11110515  321154
1  20240812  11110530  780764
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240813.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240813  11110515  318854
1  20240813  11110530  802056
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240814.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240814  11110515  341401
1  20240814  11110530  801166
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240815.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240815  11110515  333759
1  20240815  11110530  488126
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240816.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240816  11110515  347205
1  20240816  11110530  721083
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240817.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240817  11110515  335638
1  20240817  11110530  464436
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240818.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240818  11110515  326772
1  20240818  11110530  439666
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240819.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240819  11110515  335487
1  20240819  11110530  769645
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240820.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240820  11110515  337565
1  20240820  11110530  785665
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240821.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240821  11110515  344719
1  20240821  11110530  776432
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240822.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240822  11110515  346022
1  20240822  11110530  786220
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240823.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240823  11110515  355399
1  20240823  11110530  797255
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240824.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240824  11110515  342489
1  20240824  11110530  485501
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240825.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240825  11110515  327202
1  20240825  11110530  450152
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240826.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240826  11110515  339316
1  20240826  11110530  779658
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240827.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240827  11110515  339721
1  20240827  11110530  812335
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240828.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240828  11110515  351979
1  20240828  11110530  834199
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240829.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240829  11110515  353717
1  20240829  11110530  821784
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240830.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240830  11110515  355495
1  20240830  11110530  794276
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202408\250_ORGN_CT_20240831.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240831  11110515  348655
1  20240831  11110530  505586
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240901.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240901  11110515  325850
1  20240901  11110530  462139
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240902.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240902  11110515  346414
1  20240902  11110530  796315
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240903.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240903  11110515  347784
1  20240903  11110530  816249
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240904.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240904  11110515  368989
1  20240904  11110530  830995
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240905.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240905  11110515  345295
1  20240905  11110530  832503
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240906.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240906  11110515  361508
1  20240906  11110530  819696
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240907.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240907  11110515  347739
1  20240907  11110530  521753
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240908.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240908  11110515  333070
1  20240908  11110530  496063
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240909.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240909  11110515  344115
1  20240909  11110530  793513
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240910.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240910  11110515  347968
1  20240910  11110530  825052
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240911.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240911  11110515  358780
1  20240911  11110530  834536
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240912.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240912  11110515  349072
1  20240912  11110530  817535
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240913.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240913  11110515  342118
1  20240913  11110530  730614
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240914.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240914  11110515  343729
1  20240914  11110530  441101
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240915.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240915  11110515  374410
1  20240915  11110530  462730
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240916.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240916  11110515  390236
1  20240916  11110530  424762
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240917.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240917  11110515  370077
1  20240917  11110530  411573
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240918.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240918  11110515  345894
1  20240918  11110530  406870
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240919.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240919  11110515  336887
1  20240919  11110530  739314
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240920.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240920  11110515  337838
1  20240920  11110530  768776
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240921.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240921  11110515  339831
1  20240921  11110530  487249
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240922.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240922  11110515  356791
1  20240922  11110530  495418
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240923.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240923  11110515  357302
1  20240923  11110530  799210
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240924.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240924  11110515  348427
1  20240924  11110530  849573
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240925.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240925  11110515  373784
1  20240925  11110530  834761
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240926.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240926  11110515  367837
1  20240926  11110530  852160
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240927.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240927  11110515  368958
1  20240927  11110530  830627
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240928.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240928  11110515  391256
1  20240928  11110530  690796
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240929.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240929  11110515  352145
1  20240929  11110530  447805
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202409\250_ORGN_CT_20240930.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20240930  11110515  359306
1  20240930  11110530  871749
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241001.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241001  11110515  337480
1  20241001  11110530  545947
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241002.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241002  11110515  336751
1  20241002  11110530  809704
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241003.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241003  11110515  427389
1  20241003  11110530  547268
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241004.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241004  11110515  379924
1  20241004  11110530  806756
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241005.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241005  11110515  393550
1  20241005  11110530  524459
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241006.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241006  11110515  349408
1  20241006  11110530  467286
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241007.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241007  11110515  355386
1  20241007  11110530  798627
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241008.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241008  11110515  352627
1  20241008  11110530  825766
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241009.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241009  11110515  408622
1  20241009  11110530  530584
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241010.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241010  11110515  372388
1  20241010  11110530  834365
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241011.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241011  11110515  379650
1  20241011  11110530  849916
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241012.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241012  11110515  413948
1  20241012  11110530  556606
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241013.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241013  11110515  374765
1  20241013  11110530  505765
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241014.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241014  11110515  361518
1  20241014  11110530  828432
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241015.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241015  11110515  351345
1  20241015  11110530  850668
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241016.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241016  11110515  391760
1  20241016  11110530  843377
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241017.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241017  11110515  381213
1  20241017  11110530  861647
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241018.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241018  11110515  358649
1  20241018  11110530  821562
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241019.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241019  11110515  396803
1  20241019  11110530  547097
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241020.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241020  11110515  371224
1  20241020  11110530  508403
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241021.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241021  11110515  357408
1  20241021  11110530  800168
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241022.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241022  11110515  339819
1  20241022  11110530  821275
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241023.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241023  11110515  383214
1  20241023  11110530  858467
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241024.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241024  11110515  386277
1  20241024  11110530  857594
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241025.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241025  11110515  388510
1  20241025  11110530  847901
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241026.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241026  11110515  430398
1  20241026  11110530  591017
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241027.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241027  11110515  386867
1  20241027  11110530  653811
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241028.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241028  11110515  367657
1  20241028  11110530  814607
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241029.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241029  11110515  353157
1  20241029  11110530  834066
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241030.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241030  11110515  388501
1  20241030  11110530  867194
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202410\250_ORGN_CT_20241031.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241031  11110515  385484
1  20241031  11110530  862387
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241101.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241101  11110515  368413
1  20241101  11110530  816237
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241102.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241102  11110515  431120
1  20241102  11110530  577369
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241103.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241103  11110515  397303
1  20241103  11110530  530443
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241104.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241104  11110515  368890
1  20241104  11110530  811620
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241105.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241105  11110515  353662
1  20241105  11110530  837055
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241106.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241106  11110515  371002
1  20241106  11110530  830714
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241107.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241107  11110515  376961
1  20241107  11110530  828316
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241108.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241108  11110515  378673
1  20241108  11110530  811616
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241109.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241109  11110515  425346
1  20241109  11110530  605220
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241110.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241110  11110515  393763
1  20241110  11110530  524422
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241111.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241111  11110515  367796
1  20241111  11110530  809207
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241112.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241112  11110515  357486
1  20241112  11110530  827430
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241113.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241113  11110515  371061
1  20241113  11110530  836478
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241114.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241114  11110515  348146
1  20241114  11110530  810430
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241115.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241115  11110515  358554
1  20241115  11110530  815092
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241116.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241116  11110515  390237
1  20241116  11110530  600991
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241117.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241117  11110515  364031
1  20241117  11110530  485028
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241118.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241118  11110515  351919
1  20241118  11110530  794603
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241119.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241119  11110515  346903
1  20241119  11110530  812890
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241120.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241120  11110515  360342
1  20241120  11110530  825181
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241121.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241121  11110515  365144
1  20241121  11110530  835717
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241122.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241122  11110515  359715
1  20241122  11110530  811782
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241123.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241123  11110515  381544
1  20241123  11110530  557546
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241124.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241124  11110515  356296
1  20241124  11110530  491556
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241125.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241125  11110515  354079
1  20241125  11110530  799162
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241126.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241126  11110515  338955
1  20241126  11110530  819555
D:\seoulmate\서울시_행정동_인구\250_ORGN_CT_202411\250_ORGN_CT_20241127.csv 처리
갯수:427
         일자     행정동코드  생활인구합계
0  20241127  11110515  352732
1  20241127  11110530  817937

In [6]:
monthly_people_df = pd.read_csv(daily_population_name, encoding="utf-8-sig")

In [7]:
# 월단위를 생성

monthly_people_df = pd.read_csv(daily_population_name, encoding="utf-8-sig")


monthly_people_df["YYYYMM"] = pd.to_datetime(
    monthly_people_df["일자"], format="%Y%m%d").dt.strftime("%Y%m")

index_cols = [
    "YYYYMM",
    "행정동코드"
]

sum_cols = [
    "생활인구합계"
]

monthly_people_df = monthly_people_df.groupby(index_cols,as_index=False)["생활인구합계"].sum()

monthly_people_df.to_csv(monthly_population_name, index=False, encoding="utf-8-sig")


print(f"갯수: {len(monthly_people_df)}")
monthly_people_df.head(2)

갯수: 8955

   YYYYMM     행정동코드    생활인구합계
0  202408  11110515  10466681
1  202408  11110530  21399917